### ISSUE TITLE
Not using the future pattern

### ISSUE THREAD

**Issue by Rauno56** [kissjs/node-mongoskin#112]
> It is asynchronized, it use the future pattern.

Mongoskin is not using the future pattern actually. You would need promises for that.

**Comment by benjamingr** [comment]
Yes, no promises - you probably want to remove that part.

**Comment by carloscarcamo** [comment]
+1

**Comment by guileen** [comment]
Fine. When I begin to write mongoskin, there is no standard promise definition in javascript. What you guys said mongoskin is neither promises nor future, is compare to modern javascript promise, I don't like it at all.

I removed that in github project description because somebody is confused that. But, mongoskin is using promise or future design pattern, whatever you call it, you can check the definition on wikipedia:

https://en.wikipedia.org/wiki/Futures_and_promises
