### ISSUE TITLE
arrayFilters + findAndModify support 

### ISSUE THREAD

**Issue by radoslavcink** [kissjs/node-mongoskin#201]
Hello, is there a way how to use arrayFilters for findAndModify, that was introduced in MongoDb v. 3.6?

If not directly, can I somehow write and execute native query, such as I gues mongoose can?

Thanks very much for any reply.

**Comment by ar2rsawseen** [comment]
You can always use any native stuff, by getting reference to native driver. The only problem is to know when mongoskin driver becomes native, because at first it returns proxy object, and only after connection established it has native driver.

The rough code could be like this:
```
function onOpened(callback){
        if(db.isOpen())
            callback();
        else{
            db._emitter.once('open', function (err, db) {
                callback();
            });
        }
};
```

and you can use it like this
```
//we get mongoskin db object
db = mongo.db(dbName, dbOptions);
console.log(db._native); //native driver is not there yet
onOpened(function(){
    //now we can run anything we want on native driver directly, just as in MongoDB documentation
    console.log(db._native);
});
```

**Comment by radoslavcink** [comment]
> You can always use any native stuff, by getting reference to native driver. 

I didn't know that.
Many thanks for lifecycle explanation and clear example.
